import type { TemplateManifest } from "@/lib/templates/types";

export const heritageManifest: TemplateManifest = {
  id: "heritage",
  name: "Heritage",
  description: "A timeless editorial church design.",
  previewImage: "/templates/heritage/preview.svg",
  implemented: true,
  supportedSections: [
    "home",
    "about",
    "sermons",
    "sermonDetail",
    "events",
    "eventDetail",
    "ministries",
    "articles",
    "articleDetail",
    "videos",
    "give",
    "giveDetail",
    "contact",
    "prayer",
    "memberGate",
  ],
  imageSlots: [
    "hero",
    "about",
    "featuredMinistry",
    "worship",
    "socialPreview",
    "logo",
    "favicon",
  ],
};
